Add commit_grep, an analyzer that greps through commit logs
linusg/hyper-unspecific-data-parsing-and-graphing-scripts pull request #7
Opened 2023-03-30 17:07 UTC by kleinesfilmroellchen

Output from the unmodified grep plotter, since the format is compatible:

2023-03-30 19:45 UTC, kleinesfilmroellchen commented on stats/git.py
> +    return git(repository, "log", "--pretty=format:%B")
However, since the tool has options to skip commits, only considering the last commit will lead to data being lost when commits are skipped. I will add an option to switch between the two modes.

2023-03-30 21:04 UTC, kleinesfilmroellchen commented
@linusg Refactored the analyzer options some more so that they know what range of commits they are operating on, and use that information in the commit analyzer to output a log for the range. Conveniently, git rev ranges are end exclusive, so nothing will be counted twice!

2023-03-31 10:21 UTC, linusg commented on README.md
> +#### `grep_commits`
Let's put this after `grep`

2023-03-31 10:21 UTC, linusg commented on main.py
> +        result = analyzer_function(repository, end_commit=end_commit)  # type: ignore[call-arg]
That's :catdogsus:. why do we have to ignore a `call-arg` error?

2023-03-31 10:21 UTC, linusg commented on main.py
> +def process_commit(commits: tuple[Commit, Commit]) -> dict[str, Any]:
There's literally no point whatsoever in taking a two-element tuple when we could take two named arguments :)

2023-03-31 10:21 UTC, linusg commented on stats/analyzers/__init__.py
> +            Config.Analyzers.CommitGrep: lambda: partial(
rename to `GrepCommits`, move after `Grep`

2023-03-31 10:21 UTC, linusg commented on stats/analyzers/grep.py
> +from stats.git import get_files, Commit
isort:

```suggestion
from stats.git import Commit, get_files
```

2023-03-31 10:21 UTC, linusg commented on stats/analyzers/grep_commits.py
> +from stats.git import get_commit_texts, Commit, git
isort:

```suggestion
from stats.git import Commit, get_commit_texts, git
```

2023-03-31 10:21 UTC, linusg commented on stats/analyzers/grep_commits.py
> +    commit_text = str(get_commit_texts(repository, end_commit.hash))
`get_commit_texts` returns a `str`

2023-03-31 10:21 UTC, linusg commented on stats/config.py
> +                    "grep_commits": lambda: Config.Analyzers.CommitGrep(
`GrepCommits`, move up

2023-03-31 10:26 UTC, kleinesfilmroellchen commented on main.py
> +        result = analyzer_function(repository, end_commit=end_commit)  # type: ignore[call-arg]
The argument is a keyword argument, and Callable only accounts for non-keyword arguments. Since end_commit is typically the last argument, we cannot rely on passing it by value, making a change of AnalyzerFunction not possible.

FYI, I checked and there currently is no way of specifying keyword argument type annotations for Callable.

2023-03-31 10:27 UTC, kleinesfilmroellchen commented on main.py
> +def process_commit(commits: tuple[Commit, Commit]) -> dict[str, Any]:
I missed that there is `Pool.starmap`, so you are right; that would have been the blocker since map only passes one argument.

2023-03-31 10:33 UTC, linusg commented on main.py
> +        result = analyzer_function(repository, end_commit=end_commit)  # type: ignore[call-arg]
ah, fair enough

2023-03-31 10:42 UTC, linusg requested changes

2023-03-31 10:42 UTC, linusg commented on stats/analyzers/grep_commits.py
> +    commit_text = get_commit_texts(repository, end_commit.hash)
`NameError: name 'end_commit' is not defined`

(why are we using `*args` now?)

2023-03-31 10:48 UTC, kleinesfilmroellchen commented on stats/analyzers/grep_commits.py
> +    commit_text = get_commit_texts(repository, end_commit.hash)
... I don't see that error; end_commit is a positional argument of the function?

`*args` is so that the functions can ignore the positional arguments they don't need. The simple `*` from before fails ("too many positional arguments"), probably because of the `partial` indirection.

2023-03-31 10:51 UTC, linusg commented on stats/analyzers/grep_commits.py
> +    commit_text = get_commit_texts(repository, end_commit.hash)
oops, missed that param! `*args` make terrible APIs though, let's continue to explicitly name everything passed in please :)

2023-03-31 10:52 UTC, kleinesfilmroellchen commented on stats/analyzers/grep_commits.py
> +    commit_text = get_commit_texts(repository, end_commit.hash)
Again; the purpose of *args here is "any number of extra arguments that this analyzer doesn't care about", which is why I explicitly ignore it with _=*args. This will make adding further positional arguments in the future much easier.

2023-03-31 10:53 UTC, kleinesfilmroellchen commented on stats/analyzers/grep_commits.py
> +    commit_text = get_commit_texts(repository, end_commit.hash)
And as far as I can tell, *args is a standard name for "the rest of the positional arguments"

2023-03-31 11:06 UTC, linusg commented on stats/analyzers/grep_commits.py
> +    commit_text = get_commit_texts(repository, end_commit.hash)
indeed, but that doesn't mean it's good to use it when all arguments are known. This is a tiny codebase and we control all callers, we can be specific and use named args.

2023-03-31 11:15 UTC, linusg reviewed
almost there :)

2023-03-31 11:58 UTC, linusg commented on stats/git.py
> +    return git(repository, "log", "-n1", "--pretty=format:%B", f"HEAD..{end_commit}")
The more I think about it, the less I like it. Analyzers really should not run on anything but code and metadata related to _one_ commit, which a range is not. Especially after merging #10, what purpose does this serve?

2023-03-31 12:21 UTC, kleinesfilmroellchen commented on stats/git.py
> +    return git(repository, "log", "-n1", "--pretty=format:%B", f"HEAD..{end_commit}")
Since all other analyzers look at in-repo data, it is possible there to "interpolate" data for missing commits. However, this analyzer depends on specifically inspecting commits themselves. If we do not consider a commit which contains the grepped text, that commit will never show up in the final results if we don't include it in the log output.

Visually speaking, coarser sampling on other analyzers will simply make their graphs look more coarse, details are removed but the shape is the same. On this analyzer, coarser sampling without handling commit ranges will simply lead to a smaller and smaller graph, depending on your sampling luck. For example, if you are super unlucky, there may be 1000 unsampled commits with 3 occurrences of the text, meaning that a cumulative graph should steadily rise towards later dates and end up with 3000. However, since the commits are not sampled, the graph will show 0 all the way.

This is not just an issue of resolution, it's an issue of accuracy. Disregarding this issue would mean that you are forced to sample all commits to use this analyzer, which is a non-starter for large repos.

The code here has a bug: the "-n1" should be removed, as it achieves exactly the same as you are proposing.

2023-03-31 12:23 UTC, kleinesfilmroellchen commented
To reiterate on the relationship between #10 and #7: #10 simply adds up the results for individual commits or small commit ranges (depending on exact sampling behavior). **It will still show wrong results if we only grep in the last commit message.**

2023-11-09 16:44 UTC, linusg reviewed
I stand by my original concern that all analyzers should run on a single commit only, and something like `end_commit` violates that idea. This should be easily fixable by making sampling choices available per-analyzer instead of per-config, which we can do separate from this PR.

Other than that I really like this :)

2023-12-30 11:16 UTC, linusg commented on main.py
> +from itertools import zip_longest
This appears to be unused now

2023-12-30 11:16 UTC, linusg commented on stats/analyzers/grep.py
> +    repository: Path,
Let's undo these changes to make the diff smaller :)

2023-12-30 11:16 UTC, linusg commented on stats/analyzers/grep.py
> +from stats.git import Commit, get_files
Unused

2023-12-30 11:16 UTC, linusg commented on stats/analyzers/scc.py
> +from stats.git import Commit
Unused

2023-12-30 11:16 UTC, linusg commented on README.md
> +Count occurrences of strings or regular expressions in commit messages. When commit sampling is used, all relevant previous commits before the sampled commit and after the previous sampled commit are
The second part is no longer true, I think

2023-12-31 15:28 UTC, linusg approved these changes
Thanks!

2023-12-31 15:28 UTC, merged